ExperienciaTuristica/ExperienciaTuristica/Controllers/GaleriaController.cs
using Datos;
using ExperienciaTuristica.Models;
using Microsoft.Security.Application;
using RepositorioClases;
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Antlr;
using System.IO;
using System.Configuration;

namespace ExperienciaTuristica.Controllers
{
    public class GaleriaController : Controller
    {
        //
        // GET: /Galeria/

        //Va a mostrar todas las galerias
        public ActionResult Index(int? id)
        {
            List<Galeria> galeriasClase = GaleriaService.ObtenerGaleriaPorIdGaleria(id);
            List<GaleriaModel> galeriasModel = new List<GaleriaModel>();
            foreach (var gal in galeriasClase)
            {
                GaleriaModel galeria = new GaleriaModel();
                galeria.FechaHoraGaleria = gal.FechaHoraGaleria;
                galeria.DescripcionGaleria = Server.HtmlDecode(gal.DescripcionGaleria);
                galeria.IdCiudad = gal.CiudadId;
                galeria.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(gal.CiudadId).CiudadNombre;
                galeria.IdUsuario = gal.IdUsuario;
                galeria.IdGaleria = gal.IdGaleria;
                galeria.TituloGaleria = gal.TituloGaleria;

                List<Imagen> imagenes = GaleriaService.ObtenerImagenesPorGaleria(galeria.IdGaleria);
                galeria.imagenesCargadas = imagenes;

                galeriasModel.Add(galeria);
            }
            if (galeriasModel.Count != 0)
            {
                ViewBag.Mensaje = "Galerias de experiencia turística:";
            }
            else
            {
                ViewBag.Mensaje = "No existen galerias disponibles.";
            }

            return View(galeriasModel);
        }

        public ActionResult MostrarGaleria(int? id)
        {
            List<Galeria> galerias = GaleriaService.ObtenerGaleriaPorIdGaleria(id);
            List<GaleriaModel> galeriasModel = new List<GaleriaModel>();
            GaleriaModel galeria = new GaleriaModel();
            

            galeria.FechaHoraGaleria = galerias[0].FechaHoraGaleria;
            galeria.DescripcionGaleria = Server.HtmlDecode(galerias[0].DescripcionGaleria);
            galeria.IdCiudad = galerias[0].CiudadId;
            galeria.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(galerias[0].CiudadId).CiudadNombre;
            galeria.IdUsuario = galerias[0].IdUsuario;
            galeria.IdGaleria = galerias[0].IdGaleria;
            galeria.TituloGaleria = galerias[0].TituloGaleria;

            List<Imagen> imagenes = GaleriaService.ObtenerImagenesPorGaleria(galeria.IdGaleria);
            galeria.imagenesCargadas = imagenes;

            galeriasModel.Add(galeria);


            return View(galeria);
        }


        public ActionResult MisGalerias()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                List<Galeria> galeriasClase = GaleriaService.ObtenerGaleria(usu.IdUsuario);
                List<GaleriaModel> galeriasModel = new List<GaleriaModel>();
                foreach (var gal in galeriasClase)
                {
                    GaleriaModel galeria = new GaleriaModel();
                    galeria.FechaHoraGaleria = gal.FechaHoraGaleria;
                    galeria.DescripcionGaleria = Server.HtmlDecode(gal.DescripcionGaleria);
                    galeria.IdCiudad = gal.CiudadId;
                    galeria.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(gal.CiudadId).CiudadNombre;
                    galeria.IdUsuario = gal.IdUsuario;
                    galeria.IdGaleria = gal.IdGaleria;
                    galeria.TituloGaleria = gal.TituloGaleria;
                    galeriasModel.Add(galeria);
                }
                if (galeriasModel.Count != 0)
                {
                    ViewBag.Mensaje = "Estas son sus galerías:";
                }
                else
                {
                    ViewBag.Mensaje = "No tiene disponibles galerías.";
                }

                return View(galeriasModel);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        public ActionResult CrearGaleria()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                GaleriaModel galeria = new GaleriaModel();

                List<Paises> paises = PaisServicio.ObtenerPaises();
                ViewBag.paises = paises;
                List<Ciudades> ciudades = CiudadServicio.ObtenerCiudades();
                ViewBag.ciudades = ciudades;
                return View(galeria);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CrearGaleria(GaleriaModel galeria)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                Usuario usu2 = UsuarioServicio.ObtenerUsuarioPorNombre(usu.NombreUsuario);

                galeria.IdUsuario = usu2.IdUsuario;
                galeria.FechaHoraGaleria = DateTime.Now;
                galeria.DescripcionGaleria = Server.HtmlEncode(galeria.DescripcionGaleria);

                if (usu.IdRol != 0)
                {
                    if (ModelState.IsValid)
                    {
                        GaleriaService.NuevaGaleria(new RepositorioClases.Galeria()
                        {
                            CiudadId = galeria.IdCiudad,
                            DescripcionGaleria = galeria.DescripcionGaleria,
                            FechaHoraGaleria = galeria.FechaHoraGaleria,
                            TituloGaleria = galeria.TituloGaleria,
                            IdUsuario = galeria.IdUsuario
                        });

                    }
                    return RedirectToAction("MisGalerias");
                }
                else
                {
                    return RedirectToAction("Error", "General");
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        public ActionResult CargarImagenes(int IdGaleria)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                ImagenesModel model = new ImagenesModel();
                Session["IdGaleria"] = IdGaleria;
                ViewBag.IdGaleria = IdGaleria;

                List<Imagen> imagenes = GaleriaService.ObtenerImagenesPorGaleria(IdGaleria);
                model.imagenesCargadas = imagenes;

                return View(model);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        [HttpPost]
        public ActionResult CargarImagenes(ImagenesModel imagen)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                int idGaleria = (int)(Session["IdGaleria"]);
                foreach (var archivo in imagen.archivos)
                {
                    if (archivo != null)
                    {
                        if (archivo.ContentLength > 0)
                        {
                            string fileName = Path.GetFileName(archivo.FileName);
                            var pathDB = Path.Combine(ConfigurationManager.AppSettings.Get("PathImagenes"), fileName);
                            var nombreImagen = Path.Combine("Content\\Imagenes\\", fileName);
                            var aux = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, nombreImagen);
                            GaleriaService.GuardarImagen(pathDB, idGaleria);
                            archivo.SaveAs(aux);
                        }
                    }
                }
                return RedirectToAction("MisGalerias");
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        public ActionResult EditarGaleria(int IdGaleria)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                Session["IdGaleria"] = IdGaleria;
                List<Galeria> galerias = GaleriaService.ObtenerGaleriaPorIdGaleria(IdGaleria);
                GaleriaModel galeria = new GaleriaModel();

                galeria.DescripcionGaleria = Server.HtmlDecode(galerias[0].DescripcionGaleria);
                galeria.IdCiudad = galerias[0].CiudadId;
                galeria.TituloGaleria = galerias[0].TituloGaleria;

                List<Paises> paises = PaisServicio.ObtenerPaises();
                ViewBag.paises = paises;
                int? idciudad = galeria.IdCiudad;
                if (idciudad == null)
                {
                    idciudad = 0;
                }
                Paises pais = PaisServicio.ObtenerPaisPorIdCiudad(idciudad);
                ViewBag.paisseleccionado = pais.PaisCodigo;
                ViewBag.ciudadseleccionada = idciudad;

                List<Ciudades> ciudades = CiudadServicio.ObtenerCiudades();
                ViewBag.ciudades = ciudades;

                return View(galeria);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

ExperienciaTuristica/ExperienciaTuristica/Views/Galeria/CargarImagenes.cshtml
@model ExperienciaTuristica.Models.ImagenesModel

@{
    ViewBag.Title = "CargarImagenes";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<link href="~/Content/Galerias.css" rel="stylesheet" />

<h2>Imagenes de la galería</h2>

@using (Html.BeginForm("CargarImagenes", "Galeria", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    <table>
        <tr>
            <td>
                <input type="file" name="archivos" id="archivos" class="btn" style="float: left; height: 31px; padding: 4px 0px 0px 4px; margin-right: 5px;" multiple>
                <input type="submit" name="guardar" id="guardar" value="Guardar Imagenes" class="btn btn-guardar-imagenes" style="background-color: rgba(41, 41, 41, 0.9); font-weight: normal;">
            </td>
        </tr>
    </table>
}


<div id="ImagenesCargadas">
    @foreach (var imagen in @Model.imagenesCargadas)
    { 
        <div class="ImagenCargada" id="imagen_@imagen.IdImagen">
            <img src="@imagen.PathImagen">
            <i class="fa fa-times" onclick="eliminarImagen(@imagen.IdImagen)"></i>
            <i class="fa fa-bars"></i>
            <div class="popover-markup">
                <a href="#" class="triggerImagen"></a>
                <div class="head hide">Añada una descripción:</div>
                <div class="content hide">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Escriba aquí…" id="descripcion_@imagen.IdImagen" value="@imagen.DescripcionImagen">
                    </div>
                    <button type="submit" class="btn btn-default btn-block" onclick="agregarDescripcion(@imagen.IdImagen)">
                        Guardar descripción
                    </button>
                </div>
            </div>
        </div>
    }
</div>



<script type="text/javascript">
    function agregarDescripcion(IdImagen) {
        var descripcion = $("#descripcion_" + IdImagen).val();
        $.ajax({
            type: "POST",
            url: "/Galeria/ActualizarComentarioImagen/",
            data: { "descripcion": descripcion, "IdImagen": IdImagen },
            success: function (data) {
                if (data == true) {
                    location.reload();
                }
            }
        });
    }

    function eliminarImagen(IdImagen) {
        $.ajax({
            type: "POST",
            url: "/Galeria/EliminarImagen/",
            data: { "IdImagen": IdImagen },
        });
        $("#imagen_" + IdImagen).hide();
    }

    $('.triggerImagen').popover({
        html: true,
        title: function () {
            return $(this).parent().find('.head').html();
        },
        content: function () {
            return $(this).parent().find('.content').html();
        }
    });
</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Galeria/CrearGaleria.cshtml
@model ExperienciaTuristica.Models.GaleriaModel

@{
    ViewBag.Title = "NuevaGalería";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}
<link href="~/Content/Galerias.css" rel="stylesheet" />
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>

<div class="contenedor-galerias">
    <h2>Nueva Galería: </h2>

    @using (Html.BeginForm("CrearGaleria", "Galeria", FormMethod.Post, new { @id = "formulario", @novalidate = "novalidate" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Usuario</legend>

            <div class="form-galeria">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.TituloGaleria)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(Model => Model.TituloGaleria)
                    @Html.ValidationMessageFor(Model => Model.TituloGaleria)
                </div>
            </div>
            <div class="form-galeria">
                <div class="editor-label">
                    @Html.LabelFor(x => x.PaisCodigo)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.PaisCodigo, new SelectList(ViewBag.paises, "PaisCodigo", "PaisNombre"), "Selecciona un pais", new { @class = "form-control" })
                </div>
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdCiudad)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.IdCiudad, new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } }, "Selecciona una ciudad", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdCiudad)
                </div>
            </div>
            <div class="textarea-galeria">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.DescripcionGaleria)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.DescripcionGaleria)
                    @Html.ValidationMessageFor(Model => Model.DescripcionGaleria)
                </div>
            </div>
            <input type="submit" value="Crear Galería" />
        </fieldset>
        
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#PaisCodigo").change(function () {
            //Se limpia el contenido del dropdownlist
            $("#IdCiudad").empty();
            $.ajax({
                type: 'POST',
                //Llamado al metodo en el controlador
                url: '/Tema/GetCiudadbyPaisCodigo/',
                dataType: 'json',
                //Parametros que se envian al metodo del controlador
                data: { PaisCodigo: $("#PaisCodigo").val() },
                //En caso de resultado exitoso
                success: function (Ciudades) {
                    if (Ciudades.length == 0) {
                        $("#IdCiudad").append('<option value=""></option>');
                    }
                    else {
                        //Se agrega el elemento vacio para poder desplegar que seleccione una opcion
                        $("#IdCiudad").append('<option value="">Seleccione una ciudad</option>');
                        Ciudades.forEach(function (Ciudad) {
                            $("#IdCiudad").append('<option value="' + Ciudad.Value + '">' +
                            Ciudad.Text + '</option>');
                        });
                    }
                },
                //Mensaje de error en caso de fallo
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })
    });
</script>
<script type="text/javascript">
    $("#formulario").validate({
        rules: {
            TituloGaleria: 'required',
            PaisCodigo: 'required',
            IdCiudad: 'required',
            DescripcionGaleria: 'required',
        },
        messages: {
            TituloGaleria: 'Se requiere un título para la galería',
            PaisCodigo: 'Debe seleccionar un país',
            IdCiudad: 'Debe seleccionar una ciudad',
            DescripcionGaleria: 'Debe agregar una descrípción a la galería',
        },
        submitHandler: function (form) {
            form.submit();
            alert('Ahora puede cargar las fotos de su galería!!');
        }
    });

</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Galeria/EditarGaleria.cshtml
@model ExperienciaTuristica.Models.GaleriaModel

@{
    ViewBag.Title = "NuevaGalería";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}
<link href="~/Content/Galerias.css" rel="stylesheet" />

<div class="contenedor-galerias">
    <h2>Nueva Galería: </h2>

    @using (Html.BeginForm())
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Usuario</legend>

            <div class="form-galeria">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.TituloGaleria)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(Model => Model.TituloGaleria)
                    @Html.ValidationMessageFor(Model => Model.TituloGaleria)
                </div>
            </div>
            <div class="form-galeria">
                <div class="editor-label">
                    @Html.LabelFor(x => x.PaisCodigo)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.PaisCodigo, new SelectList(ViewBag.paises, "PaisCodigo", "PaisNombre"), "Selecciona un pais", new { @class = "form-control" })
                </div>
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdCiudad)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.IdCiudad, new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } }, "Selecciona una ciudad", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdCiudad)
                </div>
            </div>
            <div class="textarea-galeria">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.DescripcionGaleria)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.DescripcionGaleria)
                    @Html.ValidationMessageFor(Model => Model.DescripcionGaleria)
                </div>
            </div>
            <input type="submit" value="Editar galería" />
            @Html.TextAreaFor(Model => Model.FechaHoraGaleria, new { @class = "oculto" })
        </fieldset>
        
    }
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#PaisCodigo").change(function () {
            //Se limpia el contenido del dropdownlist
            $("#IdCiudad").empty();
            $.ajax({
                type: 'POST',
                //Llamado al metodo en el controlador
                url: '/Tema/GetCiudadbyPaisCodigo/',
                dataType: 'json',
                //Parametros que se envian al metodo del controlador
                data: { PaisCodigo: $("#PaisCodigo").val() },
                //En caso de resultado exitoso
                success: function (Ciudades) {
                    if (Ciudades.length == 0) {
                        $("#IdCiudad").append('<option value=""></option>');
                    }
                    else {
                        //Se agrega el elemento vacio para poder desplegar que seleccione una opcion
                        $("#IdCiudad").append('<option value="">Seleccione una ciudad</option>');
                        Ciudades.forEach(function (Ciudad) {
                            $("#IdCiudad").append('<option value="' + Ciudad.Value + '">' +
                            Ciudad.Text + '</option>');
                        });
                    }
                    actualizarComboCiudad();
                },
                //Mensaje de error en caso de fallo
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })

        $('#PaisCodigo> option[value=@ViewBag.paisseleccionado]').attr('selected', 'selected');
            $("#PaisCodigo").change();

        });
        function actualizarComboCiudad() {
            $('#IdCiudad> option[value=@ViewBag.ciudadseleccionada]').attr('selected', 'selected');
        }
</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Galeria/Index.cshtml
@model List<ExperienciaTuristica.Models.GaleriaModel>

@{
    ViewBag.Subject = "Visualización Galerías";
    ViewBag.Description = "Mostrará todas las galerías que se encuentren cargados en Experiencia Turística";
    ViewBag.Title = "Todos las Galerías de Experiencia Turistica";
    ViewBag.Keywords = "turismo, turistico, viaje, viajes, viajeros, viajero,aventura, excursion, paseo,paisaje, argentina, imagen, imagenes, galeria, galerias, foto, fotos, fotografia, fotografias";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
@using GridMvc.Html
<script src="~/Scripts/jquery-2.1.3.js"></script>
<script src="~/Scripts/gridmvc.js"></script>
<link href="~/Content/Gridmvc.css" rel="stylesheet" />
<link href="~/Content/Galerias.css" rel="stylesheet" />

<center>
<h1>Galerias</h1>
<div style="text-align:center; margin-bottom:10px">
    <input style="background-color: #ffffff; color: rgba(19, 19, 19, 0.69);" type="text" id="BusquedaGaleria" placeholder="Buscar...">
    <div class="popover fade bottom in" role="tooltip" id="popover-busqueda-galeria" style="  top: 40%; left: 40%; max-width: 250px; max-height: 500px; overflow-y: scroll; width:250px" hidden>
        <div class="arrow" style="left: 50%;"></div>
        <h3 class="popover-title" style="display: none;"></h3>
    </div>
</div>
@if (Session["Usuario"] != null)
{
    <a type="button" class="btn btn-default btn-xs" style="width: 30%;" href="/Galeria/CrearGaleria">Nueva Galeria</a>
}


<div class="row row-galeria">
       
        @Html.Grid(Model).Columns(columns =>
        {
            columns.Add().RenderValueAs(c => @<center><div>
                <div class="contenido-galeria">
                    <h3><label class="titulo-galeria"><a style="color:black;" href="/Galeria/MostrarGaleria?id=@Html.Raw(c.IdGaleria)">@Html.Raw(c.TituloGaleria)</a></label></h3>
                </div>
                <div class="imagenes-galeria">
                    <div id="links">
                        @foreach (var imagen in c.imagenesCargadas)
                        {
                            <div class="contenedor-imagen">
                                <a href="@imagen.PathImagen" title="@imagen.DescripcionImagen" data-gallery>
                                    <img src="@imagen.PathImagen" alt="@imagen.DescripcionImagen">
                                </a>
                            </div>
                        }
                    </div>
                </div>
                <div class="contenido-galeria">
                    <h4><label class="descripcion-galeria">@Html.Raw(c.DescripcionGaleria)</label></h4>
                </div>
                </div>
                </center>).Encoded(false).Sanitized(false).SetWidth("10%");

        }).WithPaging(8)

    </div>

</center>
<div id="blueimp-gallery" class="blueimp-gallery">
    <!-- The container for the modal slides -->
    <div class="slides"></div>
    <!-- Controls for the borderless lightbox -->
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
    <!-- The modal dialog, which will be used to wrap the lightbox content -->
    <div class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body next"></div>
                <div class="modal-footer">
                    <button type="button" style="width: 200px;" class="btn btn-default pull-left prev">
                        <i class="glyphicon glyphicon-chevron-left"></i>
                        Previous
                    </button>
                    <button type="button" style="width: 200px;" class="btn btn-default pull-right next">
                        Next
                        <i class="glyphicon glyphicon-chevron-right"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="//blueimp.github.io/Gallery/js/jquery.blueimp-gallery.min.js"></script>
<script src="~/Content/Bootstrap-Image-Gallery-master/js/bootstrap-image-gallery.min.js"></script>
<link href="~/Content/Galerias.css" rel="stylesheet" />
<script type="text/javascript">
    $(document).ready(function () {
        $(".modal.fade.slide-content.in").addClass("overflow-hidden");
    });
</script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#BusquedaGaleria").bind("keydown", function (e) {
            if (e.keyCode == '8') {
                $("#popover-busqueda-galeria").empty();
                $("#popover-busqueda-galeria").hide();
            }
            else {
                if ($("#BusquedaGaleria").val().length > 3) {
                    datos = { parametroBusqueda: $("#BusquedaGaleria").val() }
                    $.ajax({
                        type: "POST",
                        url: "/Busqueda/BuscarGaleria/",
                        data: datos,
                        success: function (data) {
                            $("#popover-busqueda-galeria").empty();
                            if (data.length == 0) {
                                $("#popover-busqueda-galeria").append("No se encontraron resultados");
                            }
                            else {
                                var intTema = 0;
                                var intComentario = 0;
                                $.each(data, function (index, value) {
                                    if (value.TipoResultado = "Galeria") {
                                        $("#popover-busqueda-galeria").append("<p><a href='/Galeria/Index?IdGaleria=" + value.Id + "'>" + value.TituloRepresentativo + "</a></p>");
                                    }
                                });
                            }
                            $("#popover-busqueda-galeria").show();


                        }
                    });
                }
            }
        });
    });
</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Galeria/MisGalerias.cshtml
@model List<ExperienciaTuristica.Models.GaleriaModel>

@{
    ViewBag.Title = "MisGalerias";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}
@using GridMvc.Html
<script src="~/Scripts/jquery-2.1.3.js"></script>
<script src="~/Scripts/gridmvc.js"></script>
<link href="~/Content/Gridmvc.css" rel="stylesheet" />

<link href="~/Content/bootstrap/css/bootstrap.css" rel="stylesheet" />
<link href="~/Content/Galerias.css" rel="stylesheet" />
<center>
<h1 style="font-size:3em;">Mis Galerias</h1>
<a type="button" class="btn btn-default btn-xs" style="width: 30%" href="/Galeria/CrearGaleria">Nueva Galería</a>
</center>

<h3>@ViewBag.Mensaje</h3>

@Html.Grid(Model).Columns(columns =>
           {   columns.Add(c => c.TituloGaleria).Titled("Título").Sortable(true).Filterable(true).SetWidth("40%");
               columns.Add(c => c.FechaHoraGaleria).Titled("Fecha").Sortable(true).Filterable(true).SetWidth("20%");
               columns.Add(c => c.NombreCiudad).Titled("Lugar").Sortable(true).Filterable(true).SetWidth("20%");
               columns.Add(c => c.IdGaleria).Titled("Acciones")
                          .Sanitized(false)
                          .Encoded(false)
                          .RenderValueAs(d => "<a href='/Galeria/CargarImagenes?IdGaleria=" + d.IdGaleria + "'><i class='fa fa-camera'></i></a>"
                                              + "<a href='/Galeria/EditarGaleria?IdGaleria=" + d.IdGaleria + "'><i class='fa fa-pencil-square-o iconos-acciones'></i></a>"
                                              + "<a href='/Galeria/EliminarGaleria?IdGaleria=" + d.IdGaleria + "'><i class='fa fa-times iconos-acciones'></i></a>").SetWidth("20%");
           }).WithPaging(8).WithMultipleFilters()