ExperienciaTuristica/ExperienciaTuristica/Controllers/PerfilController.cs
using Servicios;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RepositorioClases;
using System.Web.Mvc;
using ExperienciaTuristica.Models;
using System.IO;
using System.Configuration;
using System.Drawing;
using Datos;

namespace ExperienciaTuristica.Controllers
{
    public class PerfilController : Controller
    {
        //
        // GET: /Perfil/

        public ActionResult Index()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                PerfilModel perfil = new PerfilModel();
                perfil.IdCiudad = usu.IdCiudad;
                perfil.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(usu.IdCiudad).CiudadNombre;
                perfil.IdUsuario = usu.IdUsuario;
                perfil.Mail = usu.Mail;
                perfil.NombreUsuario = usu.NombreUsuario;
                perfil.NombreApellido = usu.NombreApellido;
                perfil.FotoPerfil = ConfigurationManager.AppSettings.Get("PathImagenes") + usu.FotoPerfil;
                perfil.Direccion = usu.Direccion;
                perfil.FechaNacimiento = usu.FechaNacimiento;
                

                return View(perfil);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para ver los perfiles de los usuarios." });
            }
        }
        
        [HttpPost]
        public ActionResult Index(ImagenModel imagen)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {

                if (imagen.File.ContentLength > 0)
                {
                    string fileName = Path.GetFileName(imagen.File.FileName);
                    var pathDB = Path.Combine(ConfigurationManager.AppSettings.Get("PathImagenes"), fileName);
                    var nombreImagen = Path.Combine("Content\\Imagenes\\", fileName);
                    var aux = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, nombreImagen);
                    imagen.File.SaveAs(aux);

                    Usuario usuarios = (Usuario)(Session["Usuario"]);
                    usuarios.FotoPerfil = fileName;
                    Session["Usuario"] = usuarios;
                    PerfilService.GuardarPerfilUsuario(usuarios, fileName);

                    PerfilModel perfil = new PerfilModel();
                    perfil.IdCiudad = usuarios.IdCiudad;
                    perfil.IdUsuario = usuarios.IdUsuario;
                    perfil.Mail = usuarios.Mail;
                    perfil.NombreUsuario = usuarios.NombreUsuario;
                    perfil.NombreApellido = usuarios.NombreApellido;
                    perfil.FotoPerfil = pathDB;

                    return View(perfil);
                }
                return RedirectToAction("/Index");
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe estar logueado para acceder a esta sección" });
            }
        }

        public ActionResult VerPerfil(int id)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                RepositorioClases.Usuario usuario = PerfilService.ObtenerUsuario(id);

                PerfilModel perfil = new PerfilModel();
                perfil.IdCiudad = usuario.IdCiudad;
                perfil.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(usuario.IdCiudad).CiudadNombre;
                perfil.IdUsuario = usuario.IdUsuario;
                perfil.Mail = usuario.Mail;
                perfil.NombreUsuario = usuario.NombreUsuario;
                perfil.NombreApellido = usuario.NombreApellido;
                if (usuario.FotoPerfil != null)
                {
                    perfil.FotoPerfil = Path.Combine(ConfigurationManager.AppSettings.Get("PathImagenes"), usuario.FotoPerfil);
                }
                return View(perfil);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para ver los perfiles de los usuarios." });
            }
        }
        public ActionResult EditarPerfil(int id)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                if (usu.IdUsuario == id)
                {
                    List<RepositorioClases.Usuario> usuarios = UsuarioServicio.ObtenerUsuario(id);
                    UsuarioModel usuario = new UsuarioModel();

                    usuario.Direccion = usuarios[0].Direccion;
                    usuario.FechaNacimiento = usuarios[0].FechaNacimiento;
                    usuario.IdCiudad = usuarios[0].IdCiudad;
                    usuario.IdUsuario = usuarios[0].IdUsuario;
                    usuario.Mail = usuarios[0].Mail;
                    usuario.NombreUsuario = usuarios[0].NombreUsuario;
                    usuario.NombreApellido = usuarios[0].NombreApellido;

                    List<Paises> paises = PaisServicio.ObtenerPaises();
                    ViewBag.paises = paises;
                    int? idciudad = usuario.IdCiudad;
                    if (idciudad == null)
                    {
                        idciudad = 0;
                    }
                    Paises pais = PaisServicio.ObtenerPaisPorIdCiudad(idciudad);
                    ViewBag.paisseleccionado = pais.PaisCodigo;
                    ViewBag.ciudadseleccionada = idciudad;

                    List<Ciudades> ciudades = CiudadServicio.ObtenerCiudades();
                    ViewBag.ciudades = ciudades;

                    List<Estados> estados = EstadoServicio.ObtenerEstados();
                    ViewBag.estados = estados;

                    return View(usuario);
        }
                else
                {
                    return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
            }
        }

        [HttpPost]
        public ActionResult EditarPerfil(UsuarioModel usuario)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                if (usu.IdUsuario == usuario.IdUsuario)
                {

                    PerfilService.EditarPerfil(new RepositorioClases.Usuario()
                    {
                        Direccion = usuario.Direccion,
                        FechaNacimiento = usuario.FechaNacimiento,
                        IdCiudad = usuario.IdCiudad,
                        IdUsuario = usuario.IdUsuario,
                        Mail = usuario.Mail,
                        NombreUsuario = usuario.NombreUsuario,
                        NombreApellido = usuario.NombreApellido,
                    });
                    Usuario us = UsuarioServicio.ObtenerUsuarioPorNombreContraseña(usu.NombreUsuario, Encriptado.DesEncriptar(usu.Contraseña), 1);
                    Session["Usuario"] = us;
                    return RedirectToAction("Index");

                }
                else
                {
                    return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
            }
        }

    }
         
}

ExperienciaTuristica/ExperienciaTuristica/Views/Perfil/EditarPerfil.cshtml
@model ExperienciaTuristica.Models.UsuarioModel
@{
    ViewBag.Title = "EditarPerfil";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<h2>EditarPerfil</h2>
<link href="~/Content/Home.css" rel="stylesheet" />
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/Sistema/Home.js"></script>

<script src="~/Scripts/jquery.validate.min.js"></script>
    <div class="row">
        @using (Html.BeginForm("EditarPerfil", "Perfil", FormMethod.Post, new { @id = "form", @novalidate = "novalidate" }))
        {
        @Html.Hidden("IdUsuario", Model.IdUsuario)
        <div class="col-md-6" style="border-style: groove;height: 372px; padding-top: 7px;">
            <div class="editor-label">
                @Html.LabelFor(model => Model.NombreApellido)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => Model.NombreApellido)
                @Html.ValidationMessageFor(model => Model.NombreApellido)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => Model.NombreUsuario)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => Model.NombreUsuario)
                @Html.ValidationMessageFor(model => Model.NombreUsuario)
            </div>
            <div class="editor-label">
                @Html.LabelFor(model => model.Mail)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Mail)
                @Html.ValidationMessageFor(model => model.Mail)
            </div>
            
            <div class="editor-label">
                @Html.LabelFor(x => x.PaisCodigo)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(x => x.PaisCodigo, new SelectList(ViewBag.paises, "PaisCodigo", "PaisNombre"), "Selecciona un pais", new { @class = "form-control" })
            </div>

            <div class="editor-label">
                @Html.LabelFor(x => x.IdCiudad)
            </div>
            <div class="editor-field">
                @Html.DropDownListFor(model => model.IdCiudad, new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } }, "Selecciona una ciudad", new { @class = "form-control" })
            </div>

        </div>
        <div class="col-md-6" style="border-style: groove;height: 372px;padding-top: 7px;">

            <div class="editor-label">
                @Html.LabelFor(model => model.Direccion)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Direccion)
                @Html.ValidationMessageFor(model => model.Direccion)
            </div>

            <div class="editor-label">
                @Html.LabelFor(model => model.FechaNacimiento)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => Model.FechaNacimiento)
                @Html.ValidationMessageFor(model => Model.FechaNacimiento)
            </div>

            <div class="modal-footer">
                <img src="~/Content/Imagenes/cargando.gif" hidden />
                <button type="submit" class="btn btn-primary" id="EnviarRegistro" onclick="mostrarCargando()">Enviar</button>
            </div>
        </div>
        }
    </div>
   
<script type="text/javascript">
    $(document).ready(function () {
        $("#PaisCodigo").change(function () {
            //Se limpia el contenido del dropdownlist
            $("#IdCiudad").empty();
            $.ajax({
                type: 'POST',
                //Llamado al metodo en el controlador
                url: '/Home/GetCiudadbyPaisCodigo/',
                dataType: 'json',
                //Parametros que se envian al metodo del controlador
                data: { PaisCodigo: $("#PaisCodigo").val() },
                //En caso de resultado exitoso
                success: function (Ciudades) {
                    if (Ciudades.length == 0) {
                        $("#IdCiudad").append('<option value=""></option>');
                    }
                    else {
                        //Se agrega el elemento vacio para poder desplegar que seleccione una opcion
                        $("#IdCiudad").append('<option value="">Seleccione una ciudad</option>');
                        Ciudades.forEach(function (Ciudad) {
                            $("#IdCiudad").append('<option value="' + Ciudad.Value + '">' +
                            Ciudad.Text + '</option>');
                        });
                    }
                    actualizarComboCiudad();
                },
                //Mensaje de error en caso de fallo
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })

        $('#PaisCodigo> option[value=@ViewBag.paisseleccionado]').attr('selected', 'selected');
        $("#PaisCodigo").change();

    });
    function actualizarComboCiudad() {
        $('#IdCiudad> option[value=@ViewBag.ciudadseleccionada]').attr('selected', 'selected');
    }
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $('#FechaNacimiento').datepicker()

    });

</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Perfil/Index.cshtml
@*@Model ExperienciaTuristica.Models.UsuarioModel*@

@{
    ViewBag.Title = "PerfilUsuario";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}
<link href="~/Content/Perfil.css" rel="stylesheet" />

@*<link href="~/Content/Admin.css" rel="stylesheet" />*@

<div class="datagrid" @*id="div-Principal-Perfil"*@ style="width: 1145px; height: 256px;">
    <table>    
        <tbody>
            <tr>
                <td>
                    <div id="div-Foto-Perfil">
                           <img src="@Model.FotoPerfil" align="left" width="100%" height="100%" style="border-radius:30px;width: 128px;height: 142px; border:1px solid" />
                    </div>
                    
                    <div id="div-Titulos-Perfil">  
                        <div class="editor-label"<>Nombre de Usuario:</div>
                        <div class="editor-label"<>Nombre y Apellido:</div>
                        <div class="editor-label"<>Mail de Usuario:</div>
                        <div class="editor-label"<>Ciudad:</div>
                        <div class="editor-label"<>Fecha de Nacimiento:</div>
                    </div>
                    <div id="div-Datos-Perfil">
                        <div class="display-field">@Model.NombreUsuario</div>
                        <div class="display-field">@Model.NombreApellido</div>
                        <div class="display-field">@Model.Mail</div>
                        <div class="display-field">@Model.NombreCiudad</div>
                        <div class="display-field">@Model.FechaNacimiento</div>
                    </div> 
                     <a href="/Perfil/EditarPerfil?id=@Model.IdUsuario" style="margin-left: 555px; font-size: 15px; text-decoration: underline;">Editar Perfil</a>
                </td>
                
                
                @using (Html.BeginForm(null , null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    <table id="table-Cargar-Foto">
                        <tr>
                            <td id="tit-Cargar-Foto">Cambiar foto de perfil:</td>
                            <td>
                                <input id="input-Cargar-Foto" type="File" name="File" value="File" multiple />
                            </td>
                        </tr>
                        <tr>
                           @* <td>&nbsp;</td>*@
                            <td>
                                <input id="btn-Cargar-Foto" type="submit" name="submit" value="Cargar" />
                            </td>
                        </tr>
                    </table>
                }

            </tr>
        </tbody>
    </table>

</div>

ExperienciaTuristica/ExperienciaTuristica/Views/Perfil/VerPerfil.cshtml
@*@Model ExperienciaTuristica.Models.UsuarioModel*@
@{
    ViewBag.Title = "VerPerfil";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<link href="~/Content/Perfil.css" rel="stylesheet" />
<div class="datagrid" @*id="div-Principal-Perfil"*@ style="width: 1145px; height: 256px;">
    <table>    
        <tbody>
            <tr>
                <td>
                    <div id="div-Foto-Perfil">
                           <img src="@Model.FotoPerfil" align="left" width="100%" height="100%" style="border-radius:30px;width: 128px;height: 142px; border:1px solid" />
                    </div>
                    
                    <div id="div-Titulos-Perfil">  
                        <div class="editor-label"<>Nombre de Usuario:</div>
                        <div class="editor-label"<>Nombre y Apellido:</div>
                        <div class="editor-label"<>Mail de Usuario:</div>
                        <div class="editor-label"<>Ciudad:</div>
                        <div class="editor-label"<>Fecha de Nacimiento:</div>
                    </div>
                    <div id="div-Datos-Perfil">
                        <div class="display-field">@Model.NombreUsuario</div>
                        <div class="display-field">@Model.NombreApellido</div>
                        <div class="display-field">@Model.Mail</div>
                        <div class="display-field">@Model.NombreCiudad</div>
                        <div class="display-field">@Model.FechaNacimiento</div>
                    </div> 

                </td>

            </tr>
        </tbody>
    </table>

</div>