ExperienciaTuristica/ExperienciaTuristica/Controllers/TemaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Datos;
using ExperienciaTuristica.Models;
using Servicios;
using RepositorioClases;
using System.Text.RegularExpressions;
using Facebook;
using System.Dynamic;
using Tweetinvi;
using Tweetinvi.Controllers;
using TweetSharp;
namespace ExperienciaTuristica.Controllers
{
    public class TemaController : Controller
    {
        //
        // GET: /Tema/
       
         
        public ActionResult Index()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            List<Tema> temasClase = TemaService.ObtenerTema(null);
            List<TemaModel> temasModel = new List<TemaModel>();
            foreach (var tem in temasClase)
            {
                TemaModel tema = new TemaModel();
                tema.FechaHoraTema = tem.FechaHoraTema;
                tema.DescripcionTema = Server.HtmlDecode(tem.DescripcionTema);
                tema.IdCiudad = tem.IdCiudad;
                tema.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(tem.IdCiudad).CiudadNombre;
                tema.IdUsuario = tem.IdUsuario;
                tema.IdTema = tem.IdTema;
                tema.TituloTema = tem.TituloTema;
                tema.IdCategoria = tem.IdCategoria;
                tema.ContenidoTema = Server.HtmlDecode(tem.ContenidoTema);

                temasModel.Add(tema);
            }
            
            List<CategoriasTemas> categorias = TemaService.ObtenerCategorias(null);
            ViewBag.listaCategorias = categorias;

            if (temasModel.Count != 0)
            {
                ViewBag.Mensaje = "Temas de experiencia turística:";
            }
            else
            {
                ViewBag.Mensaje = "No existen temas disponibles.";
            }

            return View(temasModel);
        }

        public ActionResult MisTemas()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                List<Tema> temasClase = TemaService.ObtenerTema(usu.IdUsuario);
                List<TemaModel> temasModel = new List<TemaModel>();
                foreach (var tem in temasClase)
                {
                    TemaModel tema = new TemaModel();
                    tema.FechaHoraTema = tem.FechaHoraTema;
                    tema.DescripcionTema = Server.HtmlDecode(tem.DescripcionTema);
                    tema.IdCiudad = tem.IdCiudad;
                    tema.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(tem.IdCiudad).CiudadNombre;
                    tema.IdUsuario = tem.IdUsuario;
                    tema.IdTema = tem.IdTema;
                    tema.TituloTema = tem.TituloTema;
                    tema.ContenidoTema = Server.HtmlDecode(tem.ContenidoTema);
                    tema.IdCategoria = tem.IdCategoria;
                    temasModel.Add(tema);
                }
                if (temasModel.Count != 0)
                {
                    ViewBag.Mensaje = "Estos son sus temas:";
                }
                else
                {
                    ViewBag.Mensaje = "No tiene temas disponibles.";
                }
                return View(temasModel);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        public ActionResult CrearTema()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                TemaModel tema = new TemaModel();

                List<Paises> paises = PaisServicio.ObtenerPaises();
                ViewBag.paises = paises;
                List<Ciudades> ciudades = CiudadServicio.ObtenerCiudades();
                ViewBag.ciudades = ciudades;
                List<CategoriasTemas> categorias = TemaService.ObtenerCategorias(null);
                ViewBag.categorias = categorias;
                List<Galeria> galerias = GaleriaService.ObtenerGaleria(usu.IdUsuario);
                ViewBag.galerias = galerias;
                return View(tema);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CrearTema(TemaModel tema)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                Usuario usu2 = UsuarioServicio.ObtenerUsuarioPorNombre(usu.NombreUsuario);

                tema.IdUsuario = usu2.IdUsuario;
                tema.FechaHoraTema = DateTime.Now;
                tema.DescripcionTema = Server.HtmlEncode(tema.DescripcionTema);
                string idVideo = null;
                string urlYoutube = null;
                if (tema.UrlYoutube != null)
                {
                    idVideo = Regex.Match(tema.UrlYoutube, @"(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&amp;]v=)|youtu\.be\/)([^""&amp;?\/ ]{11})").Groups[1].Value;
                    urlYoutube = "http://www.youtube.com/embed/" + idVideo;
                }

                if (usu.IdRol != 0)
                {
                    if (ModelState.IsValid)
                    {
                        TemaService.NuevoTema(new RepositorioClases.Tema()
                        {
                            IdCiudad = tema.IdCiudad,
                            DescripcionTema = Server.HtmlEncode(tema.DescripcionTema),
                            FechaHoraTema = tema.FechaHoraTema,
                            TituloTema = tema.TituloTema,
                            IdUsuario = tema.IdUsuario,
                            IdCategoria = tema.IdCategoria,
                            ContenidoTema = Server.HtmlEncode(tema.ContenidoTema),
                            UrlYoutube = urlYoutube,
                            IdGaleria = tema.IdGaleria
                        });
                    }
                    return RedirectToAction("MisTemas");
                }
                else
                {
                    return RedirectToAction("Error", "General");
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        public ActionResult EditarTema(int IdTema)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                Session["IdTema"] = IdTema;
                List<Tema> temas = TemaService.ObtenerTemaPorIdTema(IdTema);
                TemaModel tema = new TemaModel();

                tema.DescripcionTema = Server.HtmlDecode(temas[0].DescripcionTema);
                tema.IdCiudad = temas[0].IdCiudad;
                tema.TituloTema = temas[0].TituloTema;
                tema.ContenidoTema = Server.HtmlDecode(temas[0].ContenidoTema);
                tema.IdCategoria = temas[0].IdCategoria;
                tema.IdGaleria = temas[0].IdGaleria;
                tema.UrlYoutube = temas[0].UrlYoutube;
                
                List<Paises> paises = PaisServicio.ObtenerPaises();
                ViewBag.paises = paises;
                int? idciudad = tema.IdCiudad;
                if (idciudad == null)
                {
                    idciudad = 0;
                }
                Paises pais = PaisServicio.ObtenerPaisPorIdCiudad(idciudad);
                ViewBag.paisseleccionado = pais.PaisCodigo;
                ViewBag.ciudadseleccionada = idciudad;

                List<Ciudades> ciudades = CiudadServicio.ObtenerCiudades();
                ViewBag.ciudades = ciudades;

                List<CategoriasTemas> categorias = TemaService.ObtenerCategorias(null);
                ViewBag.categorias = categorias;

                List<Galeria> galerias = GaleriaService.ObtenerGaleria(usu.IdUsuario);
                ViewBag.galerias = galerias;

                return View(tema);
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Debe loguearse para acceder a esta sección" });
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditarTema(TemaModel tema)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                int idTema = (int)(Session["IdTema"]);
                Usuario usu2 = UsuarioServicio.ObtenerUsuarioPorNombre(usu.NombreUsuario);

                string idVideo = null;
                string urlYoutube = null;
                if (tema.UrlYoutube != null)
                {
                    idVideo = Regex.Match(tema.UrlYoutube, @"(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&amp;]v=)|youtu\.be\/)([^""&amp;?\/ ]{11})").Groups[1].Value;
                    urlYoutube = "http://www.youtube.com/embed/" + idVideo;
                }

                tema.IdTema = idTema;
                tema.DescripcionTema = Server.HtmlEncode(tema.DescripcionTema);
                tema.IdUsuario = usu2.IdUsuario;
                tema.FechaHoraTema = TemaService.ObtenerTemaPorIdTema(idTema)[0].FechaHoraTema;
                tema.FechaEliminacion = null;
                tema.ContenidoTema = Server.HtmlDecode(tema.ContenidoTema);
                tema.IdCategoria = tema.IdCategoria;
                tema.UrlYoutube = urlYoutube;
                tema.IdGaleria = tema.IdGaleria;
                
                if (usu.IdRol != 0)
                {
                    if (ModelState.IsValid)
                    {
                        TemaService.EditarTema(new RepositorioClases.Tema()
                        {
                            IdCiudad = tema.IdCiudad,

ExperienciaTuristica/ExperienciaTuristica/Views/Tema/CrearTema.cshtml
@model ExperienciaTuristica.Models.TemaModel
@{
    ViewBag.Title = "Crear Tema";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<link href="~/Content/Temas.css" rel="stylesheet" />
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>

<div class="contenedor-temas">
    <h2>Nuevo Tema: </h2>

    @using (Html.BeginForm("CrearTema", "Tema", FormMethod.Post, new { @id = "form-crear-tema", @novalidate = "novalidate" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Usuario</legend>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.TituloTema)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(Model => Model.TituloTema)
                    @Html.ValidationMessageFor(Model => Model.TituloTema)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdCategoria)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.IdCategoria, new SelectList(ViewBag.categorias, "IdCategoria", "DescripcionCategoria"), "Selecciona una categoria", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdCategoria)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(x => x.PaisCodigo)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.PaisCodigo, new SelectList(ViewBag.paises, "PaisCodigo", "PaisNombre"), "Selecciona un pais", new { @class = "form-control" })
                </div>
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdCiudad)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.IdCiudad, new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } }, "Selecciona una ciudad", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdCiudad)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdGaleria)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.IdGaleria, new SelectList(ViewBag.galerias, "IdGaleria", "TituloGaleria"), "Selecciona una galeria", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdGaleria)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.UrlYoutube)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.UrlYoutube)
                    <p style="font-size:8px">(Por favor no inserte enlaces de videos que pertenezcan a una lista de reproducción de youtube)</p>
                    @Html.ValidationMessageFor(Model => Model.UrlYoutube)
                </div>
            </div>
            <div class="textarea-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.DescripcionTema)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.DescripcionTema)
                    @Html.ValidationMessageFor(Model => Model.DescripcionTema)
                </div>
            </div>
            <div class="textarea-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.ContenidoTema)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.ContenidoTema)
                    @Html.ValidationMessageFor(Model => Model.ContenidoTema)
                </div>
            </div>
            <input type="submit" value="Crear Tema" />
        </fieldset>
        
    }
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#PaisCodigo").change(function () {
            //Se limpia el contenido del dropdownlist
            $("#IdCiudad").empty();
            $.ajax({
                type: 'POST',
                //Llamado al metodo en el controlador
                url: '/Tema/GetCiudadbyPaisCodigo/',
                dataType: 'json',
                //Parametros que se envian al metodo del controlador
                data: { PaisCodigo: $("#PaisCodigo").val() },
                //En caso de resultado exitoso
                success: function (Ciudades) {
                    if (Ciudades.length == 0) {
                        $("#IdCiudad").append('<option value=""></option>');
                    }
                    else {
                        //Se agrega el elemento vacio para poder desplegar que seleccione una opcion
                        $("#IdCiudad").append('<option value="">Seleccione una ciudad</option>');
                        Ciudades.forEach(function (Ciudad) {
                            $("#IdCiudad").append('<option value="' + Ciudad.Value + '">' +
                            Ciudad.Text + '</option>');
                        });
                    }
                },
                //Mensaje de error en caso de fallo
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })
    });
</script>
<script type="text/javascript">
    $("#form-crear-tema").validate({
        rules: {
            TituloTema: 'required',
            IdCategoria: 'required',
            PaisCodigo: 'required',
            IdCiudad: 'required',
            DescripcionTema: 'required',
            ContenidoTema: 'required'
        },
        messages: {
            TituloTema: 'Ingrese el título del tema',
            IdCategoria: 'Complete la categoría a la que pertenece el tema',
            PaisCodigo: 'Ingrese el País',
            IdCiudad: 'Ingrese la ciudad',
            DescripcionTema: 'Ingrese la descripción del tema',
            ContenidoTema: 'Ingrese el contenido del tema'
        }
    });

</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Tema/EditarTema.cshtml
@model ExperienciaTuristica.Models.TemaModel
@{
    ViewBag.Title = "EditarTema";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<link href="~/Content/Temas.css" rel="stylesheet" />
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>

<div class="contenedor-temas">
    <h2>Editar Tema: </h2>

    @using (Html.BeginForm("EditarTema", "Tema", FormMethod.Post, new { @id = "form-editar-tema", @novalidate = "novalidate" }))
    {
        @Html.ValidationSummary(true)
        <fieldset>
            <legend>Usuario</legend>
            @Html.LabelFor(Model => Model.IdTema, new { @style = "display: none" })
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.TituloTema)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(Model => Model.TituloTema)
                    @Html.ValidationMessageFor(Model => Model.TituloTema)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdCategoria)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.IdCategoria, new SelectList(ViewBag.categorias, "IdCategoria", "DescripcionCategoria"), "Selecciona una categoria", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdCategoria)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(x => x.PaisCodigo)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.PaisCodigo, new SelectList(ViewBag.paises, "PaisCodigo", "PaisNombre"), "Selecciona un pais", new { @class = "form-control" })
                </div>
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdCiudad)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(model => model.IdCiudad, new List<SelectListItem> { new SelectListItem { Text = "", Value = "" } }, "Selecciona una ciudad", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdCiudad)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(x => x.IdGaleria)
                </div>
                <div class="editor-field">
                    @Html.DropDownListFor(x => x.IdGaleria, new SelectList(ViewBag.galerias, "IdGaleria", "TituloGaleria"), "Selecciona una galeria", new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdGaleria)
                </div>
            </div>
            <div class="form-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.UrlYoutube)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.UrlYoutube)
                    @Html.ValidationMessageFor(Model => Model.UrlYoutube)
                </div>
            </div>
            <div class="textarea-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.DescripcionTema)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.DescripcionTema)
                    @Html.ValidationMessageFor(Model => Model.DescripcionTema)
                </div>
            </div>
            <div class="textarea-tema">
                <div class="editor-label">
                    @Html.LabelFor(Model => Model.ContenidoTema)
                </div>
                <div class="editor-field">
                    @Html.TextAreaFor(Model => Model.ContenidoTema)
                    @Html.ValidationMessageFor(Model => Model.ContenidoTema)
                </div>
            </div>
            <input type="submit" value="Modificar Tema" />
        </fieldset>
        
    }
</div>
<script type="text/javascript">
        $(document).ready(function () {
            $("#PaisCodigo").change(function () {
                //Se limpia el contenido del dropdownlist
                $("#IdCiudad").empty();
                $.ajax({
                    type: 'POST',
                    //Llamado al metodo en el controlador
                    url: '/Tema/GetCiudadbyPaisCodigo/',
                    dataType: 'json',
                    //Parametros que se envian al metodo del controlador
                    data: { PaisCodigo: $("#PaisCodigo").val() },
                    //En caso de resultado exitoso
                    success: function (Ciudades) {
                        if (Ciudades.length == 0) {
                            $("#IdCiudad").append('<option value=""></option>');
                        }
                        else {
                            //Se agrega el elemento vacio para poder desplegar que seleccione una opcion
                            $("#IdCiudad").append('<option value="">Seleccione una ciudad</option>');
                            Ciudades.forEach(function (Ciudad) {
                                $("#IdCiudad").append('<option value="' + Ciudad.Value + '">' +
                                Ciudad.Text + '</option>');
                            });
                        }
                        actualizarComboCiudad();
                    },
                    //Mensaje de error en caso de fallo
                    error: function (ex) {
                        alert('Failed to retrieve states.' + ex);
                    }
                });
                return false;
            })

            $('#PaisCodigo> option[value=@ViewBag.paisseleccionado]').attr('selected', 'selected');
            $("#PaisCodigo").change();

        });
        function actualizarComboCiudad() {
            $('#IdCiudad> option[value=@ViewBag.ciudadseleccionada]').attr('selected', 'selected');
    }
    </script>
<script type="text/javascript">
    $("#form-editar-tema").validate({
        rules: {
            TituloTema: 'required',
            IdCategoria: 'required',
            PaisCodigo: 'required',
            IdCiudad: 'required',
            DescripcionTema: 'required',
            ContenidoTema: 'required'
        },
        messages: {
            TituloTema: 'Ingrese el título del tema',
            IdCategoria: 'Complete la categoría a la que pertenece el tema',
            PaisCodigo: 'Ingrese el País',
            IdCiudad: 'Ingrese la ciudad',
            DescripcionTema: 'Ingrese la descripción del tema',
            ContenidoTema: 'Ingrese el contenido del tema'
        }
    });

</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Tema/Index.cshtml
@model List<ExperienciaTuristica.Models.TemaModel>

@{
    ViewBag.Subject = "Visualización Temas";
    ViewBag.Description = "Mostrará todos los temas que se encuentren cargados en Experiencia Turística";
    ViewBag.Title = "Todos los Temas de Experiencia Turistica";
    ViewBag.Keywords = "clima, turismo, experiencia, viaje, viajes, viajeros, viajero, aventura, excursion, viajante, auto, colectivo, avion, moto, emigrar paseo, ruta, hospedaje, paisaje, argentina, trasladarse, desplazarse, rodar, navegar, tema, temas, comentario, comentarios, discusion";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
    var index = 0;
}

@using GridMvc.Html
<script src="~/Scripts/jquery-2.1.3.js"></script>
<script src="~/Scripts/gridmvc.js"></script>
<link href="~/Content/Gridmvc.css" rel="stylesheet" />
<link href="~/Content/Temas.css" rel="stylesheet" />
<div class="row">
    <div class="col-md-8">
        <div style="text-align: center; margin-bottom: 10px;">
            <h1 style="font-size:3em;">Temas Populares</h1>
            <div style="text-align: center; margin-bottom: 10px;">
                <input style="background-color: #FFFFFF; color: rgba(19, 19, 19, 0.69);" type="text" id="BusquedaTemas" class="busqueda-temas" placeholder="Buscar...">
                <div class="popover fade bottom in" role="tooltip" id="popover-busqueda-tema" style="top: 88px; left: 250px; max-width: 275px; width: 275px; max-height: 500px; overflow-y: scroll; display: none;"
                    hidden>
                    <div class="arrow" style="left: 50%;"></div>
                    <h3 class="popover-title" style="display: none;"></h3>
                </div>
            </div>
            @if (Session["Usuario"] != null)
            {
                <a type="button" class="btn btn-default btn-xs" style="width: 30%;" href="/Tema/CrearTema">Nuevo Tema</a>  
            }

        </div>

        @Html.Grid(Model).Columns(columns =>
           {
           columns.Add().RenderValueAs(c => @<div class="panel-group" id="acordeon">

               <div class="panel panel-default">
                   <div class="panel-heading">
                       <h4 class="panel-title">
                           <a class="accordion-toggle" style="color:black;" data-toggle="collapse" data-parent="#acordeon" href="#collapse_@index">@Html.Raw(c.TituloTema)
                           </a>
                       </h4>
                   </div>
                   <div id="collapse_@index" class="panel-collapse collapse">
                       <div class="panel-body">
                           @Html.Raw(c.DescripcionTema)
                       </div>
                       <center><a type="button" style="color:black;" class="btn btn-default btn-xs" href="/Tema/MostrarTema?IdTema=@Html.Raw(c.IdTema)">Asistir al debate</a></center>
                   </div>
               </div>
               @{index++;}

           </div>).Encoded(false).Sanitized(false).SetWidth("10%");

           }).WithPaging(5)

        @*//@Html.Grid(Model).Columns(columns =>
        //   {
        //       columns.Add(c => c.IdTema).Titled("Título del tema")
        //                  .Sanitized(false)
        //                  .Encoded(false)
        //                  .RenderValueAs(d => "<i class='fa fa-caret-right'><a style='color:black; font-size: large;' href='/Tema/MostrarTema?IdTema=" + d.IdTema + "'>" + d.TituloTema + "</a></i><br>" +
        //                  "<div id='div-descripcion-tema' onclick='createEllipsis()'><p>" + d.DescripcionTema + "</p></div>");

        //   }).WithPaging(8)

    *@
    </div>
    <div class="col-md-4">
        <h3>Categorías</h3>

        @foreach (var cat in ViewBag.listaCategorias)
        {
            <p style="margin-bottom: 5px; margin-top:5px;"><a href="/Tema/MostrarTemasPorCategoria?IdCategoria=@cat.IdCategoria">@cat.DescripcionCategoria</a></p>
        }
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $("#BusquedaTemas").bind("keydown", function (e) {
            if (e.keyCode == '8') {
                $("#popover-busqueda-tema").empty();
                $("#popover-busqueda-tema").hide();
            }
            else {
                if ($("#BusquedaTemas").val().length > 3) {
                    datos = { parametroBusqueda: $("#BusquedaTemas").val() }
                    $.ajax({
                        type: "POST",
                        url: "/Busqueda/BuscarTema/",
                        data: datos,
                        success: function (data) {
                            $("#popover-busqueda-tema").empty();
                            if (data.length == 0) {
                                $("#popover-busqueda-tema").append("No se encontraron resultados");
                            }
                            else {
                                var intTema = 0;
                                var intComentario = 0;
                                var intCategoria = 0;
                                $.each(data, function (index, value) {
                                    if (value.TipoResultado == "Tema") {
                                        if (intTema == 0) {
                                            $("#popover-busqueda-tema").append("<div style='padding-left:3px; font-weight:bold;'>Tema</div>");
                                            intTema = 1;
                                        }
                                        $("#popover-busqueda-tema").append("<div style='padding-left: 20px; padding-right: 5px;'><a style='text-decoration: none' href='/Tema/MostrarTema?IdTema=" + value.Id + "'>" + value.TituloRepresentativo + "</a></div>");
                                    }
                                    else if (value.TipoResultado == "Comentario") {
                                        if (intComentario == 0) {
                                            $("#popover-busqueda-tema").append("<div style='padding-left:3px; font-weight:bold;'>Comentario</div>");
                                            intComentario = 1;
                                        }
                                        $("#popover-busqueda-tema").append("<div style='padding-left: 20px; padding-right: 5px;'><a style='text-decoration: none' href='/Tema/MostrarTema?IdTema=" + value.Id + "'>" + value.TituloRepresentativo + "</a></div>");
                                    }
                                    else if (value.TipoResultado == "Categoría") {
                                        if (intCategoria == 0) {
                                            $("#popover-busqueda-tema").append("<div style='padding-left:3px; font-weight:bold;'>Categoría</div>");
                                            intCategoria = 1;
                                        }
                                        $("#popover-busqueda-tema").append("<div style='padding-left: 20px; padding-right: 5px;'><a style='text-decoration: none' href='/Tema/MostrarTemasPorCategoria?IdCategoria=" + value.Id + "'>" + value.TituloRepresentativo + "</a></div>");
                                    }
                                });
                            }

                            $("#popover-busqueda-tema").show();
                        }
                    });
                }
            }
        });
    });
</script>