ExperienciaTuristica/ExperienciaTuristica/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Servicios;
using RepositorioClases;
using ExperienciaTuristica.Models;
using Datos;

namespace ExperienciaTuristica.Controllers
{
    public class UsuariosController : Controller
    {
        //
        // GET: /Usuarios/
        public ActionResult Index()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                if (usu.IdRol == 1)
                {
                    List<RepositorioClases.Usuario> usuarios = UsuarioServicio.ObtenerUsuario(null);
                    List<UsuarioModel> usuariosModels = new List<UsuarioModel>();

                    foreach (RepositorioClases.Usuario u in usuarios)
                    {
                        UsuarioModel usuario = new UsuarioModel();
                        usuario.Direccion = u.Direccion;
                        usuario.FechaNacimiento = u.FechaNacimiento;
                        usuario.IdEstado = u.IdEstado;
                        usuario.IdCiudad = u.IdCiudad;
                        usuario.IdRol = u.IdRol;
                        usuario.IdUsuario = u.IdUsuario;
                        usuario.Mail = u.Mail;
                        usuario.NombreUsuario = u.NombreUsuario;
                        usuario.NombreApellido = u.NombreApellido;
                        usuario.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(u.IdCiudad).CiudadNombre;
                        usuario.DescripcionRol = RolServicio.ObtenerRolPorIdRol(u.IdRol).DescripcionRol;
                        usuario.DescripcionBloqueo = EstadoServicio.ObtenerEstadoPorIdEstado(u.IdEstado).DescripcionBloqueo;

                        usuariosModels.Add(usuario);
                    }

                    ViewBag.NombreUsuario = (string)(Session["NombreUsuario"]);

                    return View(usuariosModels);
                }
                else
                {
                    return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión como administrador." });
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
            }
        }

        public ActionResult DetalleUsuario(int id)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                if (usu.IdRol == 1)
                {
                    List<RepositorioClases.Usuario> usuarios = UsuarioServicio.ObtenerUsuario(id);
                    UsuarioModel usuario = new UsuarioModel();

                    usuario.Direccion = usuarios[0].Direccion;
                    usuario.FechaNacimiento = usuarios[0].FechaNacimiento;
                    usuario.IdEstado = usuarios[0].IdEstado;
                    usuario.IdCiudad = usuarios[0].IdCiudad;
                    usuario.IdRol = usuarios[0].IdRol;
                    usuario.IdUsuario = usuarios[0].IdUsuario;
                    usuario.Mail = usuarios[0].Mail;
                    usuario.NombreUsuario = usuarios[0].NombreUsuario;
                    usuario.NombreApellido = usuarios[0].NombreApellido;
                    usuario.NombreCiudad = CiudadServicio.ObtenerCiudadPorIdCiudad(usuarios[0].IdCiudad).CiudadNombre;
                    usuario.DescripcionRol = RolServicio.ObtenerRolPorIdRol(usuarios[0].IdRol).DescripcionRol;
                    usuario.DescripcionBloqueo = EstadoServicio.ObtenerEstadoPorIdEstado(usuarios[0].IdEstado).DescripcionBloqueo;

                    return View(usuario);
                }
                else
                {
                    return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión como administrador." });
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
            }
        }

        //Nuevo Usuario

        public ActionResult CrearUsuario()
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                if (usu.IdRol == 1)
                {
                    UsuarioModel usuario = new UsuarioModel();

                    List<Paises> paises = PaisServicio.ObtenerPaises();
                    ViewBag.paises = paises;

                    List<Ciudades> ciudades = CiudadServicio.ObtenerCiudades();
                    ViewBag.ciudades = ciudades;

                    List<Estados> estados = EstadoServicio.ObtenerEstados();
                    ViewBag.estados = estados;

                    List<Roles> roles = RolServicio.ObtenerRoles();
                    ViewBag.roles = roles;
                    return View(usuario);
                }
                else
                {
                    return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión como administrador." });
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
            }
        }

        [HttpPost]
        public JsonResult CrearUsuario(UsuarioModel usuario)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu.IdRol == 1)
            {
                if (ModelState.IsValid)
                {
                    if (UsuarioServicio.ControlarUsuarioRepetido(usuario.Mail) == false)
                    {
                        UsuarioServicio.NuevoUsuario(new RepositorioClases.Usuario()
                        {
                            Contraseña = Encriptado.Encriptar(usuario.Contraseña),
                            Direccion = usuario.Direccion,
                            FechaNacimiento = usuario.FechaNacimiento,
                            IdEstado = 1,
                            IdCiudad = usuario.IdCiudad,
                            IdRol = usuario.IdRol,
                            IdUsuario = usuario.IdUsuario,
                            Mail = usuario.Mail,
                            NombreUsuario = usuario.NombreUsuario,
                            NombreApellido = usuario.NombreApellido,
                        });
                        return Json("Correcto", JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        return Json("ErrorUsuarioRepetido", JsonRequestBehavior.AllowGet);
                    }
                }
                return Json("ErrorModelo", JsonRequestBehavior.AllowGet);
            }
            return Json("ErrorPermiso", JsonRequestBehavior.AllowGet);
        }

        public ActionResult EditarUsuario(int id)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                if (usu.IdRol == 1)
                {
                    List<RepositorioClases.Usuario> usuarios = UsuarioServicio.ObtenerUsuario(id);
                    UsuarioModel usuario = new UsuarioModel();

                    usuario.Contraseña = usuarios[0].Contraseña;
                    usuario.Direccion = usuarios[0].Direccion;
                    usuario.FechaNacimiento = usuarios[0].FechaNacimiento;
                    usuario.IdEstado = usuarios[0].IdEstado;
                    usuario.IdCiudad = usuarios[0].IdCiudad;
                    usuario.IdRol = usuarios[0].IdRol;
                    usuario.IdUsuario = usuarios[0].IdUsuario;
                    usuario.Mail = usuarios[0].Mail;
                    usuario.NombreUsuario = usuarios[0].NombreUsuario;
                    usuario.NombreApellido = usuarios[0].NombreApellido;
                    usuario.FotoPerfil = usuarios[0].FotoPerfil;

                    List<Paises> paises = PaisServicio.ObtenerPaises();
                    ViewBag.paises = paises;
                    int? idciudad = usuario.IdCiudad;
                    if (idciudad == null)
                    {
                        idciudad = 0;
                    }
                    Paises pais = PaisServicio.ObtenerPaisPorIdCiudad(idciudad);
                    ViewBag.paisseleccionado = pais.PaisCodigo;
                    ViewBag.ciudadseleccionada = idciudad;

                    List<Ciudades> ciudades = CiudadServicio.ObtenerCiudades();
                    ViewBag.ciudades = ciudades;

                    List<Estados> estados = EstadoServicio.ObtenerEstados();
                    ViewBag.estados = estados;

                    return View(usuario);
                }
                else
                {
                    return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión como administrador." });
                }
            }
            else
            {
                return RedirectToAction("Error", "General", new { mensaje = "Usted debe iniciar sesión." });
            }
        }

        [HttpPost]
        public ActionResult EditarUsuario(UsuarioModel usuario)
        {
            Usuario usu = (Usuario)(Session["Usuario"]);
            if (usu != null)
            {
                if (usu.IdRol == 1)
                {
                    if (ModelState.IsValid)
                    {
                        UsuarioServicio.EditarUsuario(new RepositorioClases.Usuario()
                        {
                            Contraseña = usuario.Contraseña,
                            Direccion = usuario.Direccion,
                            FechaNacimiento = usuario.FechaNacimiento,
                            IdEstado = usuario.IdEstado,
                            IdCiudad = usuario.IdCiudad,
                            IdRol = usuario.IdRol,
                            IdUsuario = usuario.IdUsuario,
                            Mail = usuario.Mail,

ExperienciaTuristica/ExperienciaTuristica/Views/Usuarios/CrearUsuario.cshtml
@model ExperienciaTuristica.Models.UsuarioModel

@{
    ViewBag.Title = "CrearUsuario";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml"; 
}

<h2>Crear Usuario</h2>
<strong style="color: red;">@ViewBag.Mensaje </strong>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Usuario</legend>

        @Html.Partial("_CrearOEditar", Model)

        <p>
            <input id="btn-guardar" type="button" value="Crear" onclick="guardarUsuario()" hidden />
        </p>

    </fieldset>
}
<script src="~/Scripts/jquery-2.1.3.js"></script>
<script src="~/Scripts/bootstrap-datepicker.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#FechaNacimiento").datepicker();

        $("#label-estado").css("display", "none");
        $("#field-estado").css("display", "none");

        $("#PaisCodigo").change(function () {
            //Se limpia el contenido del dropdownlist
            $("#IdCiudad").empty();
            $.ajax({
                type: 'POST',
                //Llamado al metodo en el controlador
                url: '/Home/GetCiudadbyPaisCodigo/',
                dataType: 'json',
                //Parametros que se envian al metodo del controlador
                data: { PaisCodigo: $("#PaisCodigo").val() },
                //En caso de resultado exitoso
                success: function (Ciudades) {
                    if (Ciudades.length == 0) {
                        $("#IdCiudad").append('<option value=""></option>');
                    }
                    else {
                        //Se agrega el elemento vacio para poder desplegar que seleccione una opcion
                        $("#IdCiudad").append('<option value="">Seleccione una ciudad</option>');
                        Ciudades.forEach(function (Ciudad) {
                            $("#IdCiudad").append('<option value="' + Ciudad.Value + '">' +
                            Ciudad.Text + '</option>');
                        });
                    }
                },
                //Mensaje de error en caso de fallo
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })
    });

    function guardarUsuario() {
        var data = {
            Contraseña: $("#Contrase_a").val(),
            Direccion: $("#Direccion").val(),
            FechaNacimiento: $("#FechaNacimiento").val(),
            IdEstado: $("#IdEstado").val(),
            IdCiudad: $("#IdCiudad").val(),
            IdRol: $("#IdRol").val(),
            IdUsuario: $("#IdUsuario").val(),
            Mail: $("#Mail").val(),
            NombreUsuario: $("#NombreUsuario").val(),
            NombreApellido: $("#NombreApellido").val(),
        };
        if ($("#IdCiudad").val() == "") {
            alert("Por favor complete todos los campos solicitados.");
        }
        else {
            $.ajax({
                type: 'POST',
                url: '/Usuarios/CrearUsuario/',
                dataType: 'json',
                data: data,
                success: function (resultado) {
                    if (resultado == "ErrorUsuarioRepetido") {
                        alert("El mail de usuario ya está siendo utilizado por otro usuario.");
                    }
                    else {
                        if (resultado == "ErrorModelo") {
                            alert("Por favor complete todos los campos solicitados.");
                        }
                        else {
                            alert("Usuario creado correctamente.");
                            window.location.href = "@Url.Action("Index","Usuarios")";
                        }
                    }
                }
            });
        }
    }
</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Usuarios/DetalleUsuario.cshtml
@model ExperienciaTuristica.Models.UsuarioModel

@{
    ViewBag.Title = "DetalleUsuario";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}
<link href="~/Content/Admin.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="titulo-index">
            <h2>Detalles del usuario: @Model.NombreApellido</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <div class="datagrid">
                <table>
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="2">
                                <div id="paging">
                                    <ul>
                                        <li><a href="/Usuarios/EditarUsuario/@Model.IdUsuario">Editar</a></li>
                                        <li><a href="/Usuarios/Index">Volver</a></li>
                                    </ul>
                                </div>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <fieldset>
                                <legend>Usuario</legend>
                                <td style="width: 50%; text-align: right;">
                                    <div class="display-label">Nombre de usuario:</div>
                                    <div class="display-label">Correo electrónico:</div>
                                    <div class="display-label">Rol:</div>
                                    <div class="display-label">Ciudad:</div>
                                    <div class="display-label">Direccion:</div>
                                    <div class="display-label">Fecha de nacimiento:</div>
                                    <div class="display-label">Estado:</div>
                                </td>
                                <td>
                                    <div class="display-field">@Model.NombreUsuario</div>
                                    <div class="display-field">@Model.Mail</div>
                                    <div class="display-field">@Model.DescripcionRol</div>
                                    <div class="display-field">@Model.NombreCiudad</div>
                                    <div class="display-field">@Model.Direccion</div>
                                    <div class="display-field">@Model.FechaNacimiento</div>
                                    <div class="display-field">@Model.DescripcionBloqueo</div>
                                </td>
                            </fieldset>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>

ExperienciaTuristica/ExperienciaTuristica/Views/Usuarios/EditarUsuario.cshtml
@model ExperienciaTuristica.Models.UsuarioModel

@{
    ViewBag.Title = "Editar Usuario";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}

<h2>Editar Usuario</h2>
@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Usuario</legend>

        @Html.HiddenFor(model => model.IdUsuario)
        @Html.Partial("_CrearOEditar", Model)

        <p>
            <input id="btn-guardar" type="submit" value="Guardar" hidden />
        </p>
    </fieldset>
}

<script src="~/Scripts/jquery-2.1.3.js"></script>
<script type="text/javascript">
    $("#label-contra").css("display", "none");
    $("#field-contra").css("display", "none");
</script>
<script type="text/javascript">
    $(document).ready(function () {
        $("#PaisCodigo").change(function () {
            //Se limpia el contenido del dropdownlist
            $("#IdCiudad").empty();
            $.ajax({
                type: 'POST',
                //Llamado al metodo en el controlador
                url: '/Home/GetCiudadbyPaisCodigo/',
                dataType: 'json',
                //Parametros que se envian al metodo del controlador
                data: { PaisCodigo: $("#PaisCodigo").val() },
                //En caso de resultado exitoso
                success: function (Ciudades) {
                    debugger;
                    if (Ciudades.length == 0) {
                        $("#IdCiudad").append('<option value=""></option>');
                    }
                    else {
                        //Se agrega el elemento vacio para poder desplegar que seleccione una opcion
                        $("#IdCiudad").append('<option value="">Seleccione una ciudad</option>');
                        Ciudades.forEach(function (Ciudad) {
                            $("#IdCiudad").append('<option value="' + Ciudad.Value + '">' +
                            Ciudad.Text + '</option>');
                        });
                    }
                    actualizarComboCiudad();
                },
                //Mensaje de error en caso de fallo
                error: function (ex) {
                    alert('Failed to retrieve states.' + ex);
                }
            });
            return false;
        })

        $('#PaisCodigo> option[value=@ViewBag.paisseleccionado]').attr('selected', 'selected');
        $("#PaisCodigo").change();

    });
    function actualizarComboCiudad() {
        $('#IdCiudad> option[value=@ViewBag.ciudadseleccionada]').attr('selected', 'selected');
    }
</script>

ExperienciaTuristica/ExperienciaTuristica/Views/Usuarios/EliminarUsuario.cshtml
@model ExperienciaTuristica.Models.UsuarioModel
@{
    ViewBag.Title = "EliminarUsuario";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}
<link href="~/Content/Admin.css" rel="stylesheet" />

<div class="container">
    <div class="row">
        <div class="titulo-index">
            <h2>Eliminar Usuario: @Model.NombreApellido</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
        </div>
        <div class="col-md-4">
            <div class="datagrid">
                <table>
                    <thead>
                        <tr>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <td colspan="2">
                                <div id="paging">
                                    @using (Html.BeginForm())
                                    {
                                            <input type="submit" value="Eliminar" class="boton-eliminar"/>
                                            <li><a href="/Usuarios/Index" style="float: right">Volver</a></li>
                                    }
                                </div>
                        </tr>
                    </tfoot>
                    <tbody>
                        <tr>
                            <fieldset>
                                <legend>Usuario</legend>
                                <td style="width: 50%; text-align: right;">
                                    <div class="display-label">Nombre de usuario:</div>
                                    <div class="display-label">Correo electrónico:</div>
                                    <div class="display-label">Rol:</div>
                                    <div class="display-label">Ciudad:</div>
                                    <div class="display-label">Direccion:</div>
                                    <div class="display-label">Fecha de nacimiento:</div>
                                    <div class="display-label">Estado:</div>
                                </td>
                                <td>
                                    <div class="display-field">@Model.NombreUsuario</div>
                                    <div class="display-field">@Model.Mail</div>
                                    <div class="display-field">@Model.IdRol</div>
                                    <div class="display-field">@Model.IdCiudad</div>
                                    <div class="display-field">@Model.Direccion</div>
                                    <div class="display-field">@Model.FechaNacimiento</div>
                                    <div class="display-field">@Model.IdEstado</div>
                                </td>
                            </fieldset>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4">
        </div>
    </div>
</div>




@*<h2>EliminarUsuario</h2>

<h3>¿Desea confirmar la eliminación del usuario?</h3>
<fieldset>
    <legend>Usuario</legend>

    <div class="display-label">Nombre</div>
    <div class="display-field">@Model.NombreUsuario</div>

    <div class="display-label">Nombre</div>
    <div class="display-field">@Model.NombreApellido</div>

    <div class="display-label">Correo electrónico</div>
    <div class="display-field">@Model.Mail</div>

    <div class="display-label">Rol</div>
    <div class="display-field">@Model.IdRol</div>

    <div class="display-label">Rol</div>
    <div class="display-field">@Model.IdCiudad</div>

    <div class="display-label">Rol</div>
    <div class="display-field">@Model.Direccion</div>

    <div class="display-label">Rol</div>
    <div class="display-field">@Model.FechaNacimiento</div>

    <div class="display-label">Rol</div>
    <div class="display-field">@Model.IdEstado</div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Eliminar" /> |
        @Html.ActionLink("Volver al listado", "Index")
    </p>
}*@

ExperienciaTuristica/ExperienciaTuristica/Views/Usuarios/Index.cshtml
@model List<ExperienciaTuristica.Models.UsuarioModel>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutUsuario.cshtml";
}
@using GridMvc.Html
<script src="~/Scripts/jquery-2.1.3.js"></script>
<script src="~/Scripts/gridmvc.js"></script>
<link href="~/Content/Gridmvc.css" rel="stylesheet" />

<link href="~/Content/Admin.css" rel="stylesheet" />
<center>
    <h2 style="margin-bottom: 0.5em;">Listado de usuarios</h2>
    <a type="button" class="btn btn-default btn-xs" style="width: 30%;" href="/Usuarios/CrearUsuario">Nuevo Usuario</a>  
</center>
@Html.Grid(Model).Columns(columns =>
           {
               columns.Add(c => c.NombreUsuario).Titled("Nombre de Usuario").Sortable(true).Filterable(true).SetWidth("10%");
               columns.Add(c => c.NombreApellido).Titled("Nombre y Apellido").Sortable(true).Filterable(true).SetWidth("10%");
               columns.Add(c => c.Mail).Titled("Mail").Sortable(true).Filterable(true).SetWidth("20%");
               columns.Add(c => c.DescripcionRol).Titled("Rol").Sortable(true).Filterable(true).SetWidth("10%");
               columns.Add(c => c.NombreCiudad).Titled("Ciudad").Sortable(true).Filterable(true).SetWidth("10%");
               columns.Add(c => c.Direccion).Titled("Direccion").Sortable(true).Filterable(true).SetWidth("10%");
               columns.Add(c => c.DescripcionBloqueo).Titled("Bloqueo").Sortable(true).Filterable(true).SetWidth("10%");
               columns.Add(c => c.IdUsuario).Titled("")
                          .Sanitized(false)
                          .Encoded(false)
                          .RenderValueAs(d => "<a href='/Usuarios/DetalleUsuario/" + d.IdUsuario + "'><i class='fa fa-search-plus iconos-acciones'></i></a>"
                                              + "<a href='/Usuarios/EditarUsuario/" + d.IdUsuario + "'><i class='fa fa-pencil-square-o iconos-acciones'></i></a>"
                                              + "<a href='/Usuarios/EliminarUsuario/" + d.IdUsuario + "'><i class='fa fa-times iconos-acciones'></i></a>").SetWidth("20%");
           }).WithPaging(8).WithMultipleFilters()

<script type="text/javascript">
    $(document).ready(function () {
        $('#div-usuario-logueado').removeClass('no-visible');
        $('#div-botones').removeClass('no-visible');

    });
</script>